// /api/analyze — Edge Function (Vercel)
export const config = { runtime: "edge" };

const SYSTEM_PROMPT = `
Tu es "The Soulset Navigator", une voix douce et poétique alignée avec la marque SoulsetJourney.
Ta mission : clarifier un dilemme en 4 sections (FR), concises mais profondes :
1) 🌫 Lecture énergétique — ce que révèle le dilemme (conflits internes, besoins de l'âme)
2) 🪞 Clarity Insight — une prise de conscience concrète, sans blâmer
3) 🕯 Rituel — micro-pratique réalisable en < 5 minutes (respiration 4–6–8, écriture, marche consciente)
4) 🗣 Parole de guidance — courte phrase/mantra au ton SoulsetJourney

Contraintes :
- Ton doux, rassurant, non-moraliste (images lumineuses : ciel, horizon, souffle)
- 5 à 8 lignes max
- Pas d'avis médical, financier ou juridique
- Tu peux proposer 1 "Option produit" en 5 mots max si pertinent, format : Option produit : <nom>
`;

export default async function handler(req) {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ ok:false, error:"Method not allowed" }), { status: 405 });
  }

  // Lire le corps JSON (robuste) et accepter text|dilemma
  let bodyIn;
  try { bodyIn = await req.json(); }
  catch { return new Response(JSON.stringify({ ok:false, error:"Invalid JSON body" }), { status: 400 }); }

  const userText = (bodyIn?.text ?? bodyIn?.dilemma ?? "").toString().trim();
  if (!userText) {
    return new Response(JSON.stringify({ ok:false, error:"Missing text/dilemma" }), { status: 400 });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ ok:false, error:"Missing OPENAI_API_KEY" }), { status: 500 });
  }

  // Messages pour Chat Completions
  const messages = [
    { role: "system", content: SYSTEM_PROMPT },
    { role: "user", content: `Dilemme : ${userText}` }
  ];

  // Essaie d'abord gpt-4o-mini (rapide/éco), sinon gpt-4o en fallback si besoin
  const modelsToTry = ["gpt-4o-mini", "gpt-4o"];

  for (const model of modelsToTry) {
    try {
      const r = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model,
          messages,
          temperature: 0.8
        })
      });

      const data = await r.json();

      if (!r.ok) {
        // Log côté serveur pour debug dans Runtime Logs
        console.log("OpenAI chat error:", model, data);
        // essaie le modèle suivant
        continue;
      }

      const out =
        data?.choices?.[0]?.message?.content?.trim() || "";

      if (!out) {
        console.log("Empty completion content for model:", model, data);
        continue;
      }

      // Suggestion produit simple (heuristique)
      let product = null;
      const low = userText.toLowerCase();
      if (/(stress|dormi|sommeil|anx|angoisse)/.test(low)) product = "Diffuseur ‘Lune Zen’";
      else if (/(dispers|choisir|trop d'options|focus)/.test(low)) product = "Lampe d’ambiance ‘Focus’";
      else if (/(creativ|inspiration|idée|idee)/.test(low)) product = "ASTRO-MIND Projector";

      return new Response(
        JSON.stringify({ ok:true, text: out, markdown: out, result: out, modelUsed: model, product }),
        { status: 200, headers: { "Content-Type": "application/json" } }
      );
    } catch (e) {
      console.log("Server fetch error:", model, e?.message || e);
      // essaie le modèle suivant
      continue;
    }
  }

  // Si aucun modèle n’a produit de texte :
  return new Response(JSON.stringify({ ok:false, error:"No output generated by models" }), { status: 500 });
}
